[package]
name = "byebyemenu"
version = "0.3.0"
edition = "2024"

[dependencies]
env_logger = "0.11"
gdk = { version = "0.9", package = "gdk4", features = ["v4_12"] }
gtk = { version = "0.9", package = "gtk4", features = ["v4_12"] }
log = "0.4"
shell-words = "1.1"
