name: Cargo Build & Test
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
permissions: {}
jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Install system packages
        run: sudo apt-get install libglib2.0-dev libgdk-pixbuf-2.0-dev
      - name: Update Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
